function [dictionary,dictionary_counts]=SNLP_loadDictionary(filename);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%Open a dictionary TXT file generated by Word2Vec
%%%%
%%%%Usage:
%%%%	[dictionary,dictionary_counts]=SNLP_loadDictionary(filename)
%%%%
%%%%	filename: a UTF-8 TXT dictionary word2vec file to be loaded
%%%%
%%%%	dictionary: the list of words
%%%%	dictionary_counts: the occurrence for each word
%%%%
%%%%
%%%%	Sane Natural Language Processing Toolkit, v0.01. https://github.com/giacomohandjaras/SaneNLP_toolbox
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

dictionary=SNLP_loadWords(filename);
%%%%%%%%%the first row should be </s> and it will be discarded
dictionary(1)=[];
dictionary=split(dictionary,' ');

dictionary_counts=cellfun(@str2num, dictionary(1:end,2));
dictionary=dictionary(:,1); %%%Keep words only
	
end
