function SNLP_convertW2VtoMAT(filename,columns,language)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%Save word-embeddings generated by Word2Vec to a Matlab struct
%%%%
%%%%Usage:
%%%%	SNLP_convertW2VtoMAT(filename,columns,language)
%%%%
%%%%	filename: the file containing the word-embeddings in txt format (-binary option in w2v set to 0)
%%%%	columns: the number of dimensions of the word-embeddings (-size option in w2v)
%%%%	language: a string containing either 'ita', 'eng', 'fra', or 'none' to stem in advance the word list
%%%%
%%%%
%%%%	Sane Natural Language Processing Toolkit, v0.01. https://github.com/giacomohandjaras/SaneNLP_toolbox
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

ITA=0;
ENG=0;
FRA=0;
stemming=0;

lang=lower(language);
if(strcmp(lang,'ita'))
    ITA=1;
    ENG=0;
    FRA=0;
    stemming=1;
end
if(strcmp(lang,'eng'))
    ITA=0;
    ENG=1;
    FRA=0;
    stemming=1;
end
if(strcmp(lang,'fra'))
    ITA=0;
    ENG=0;
    FRA=1;
    stemming=1;
end


disp(sprintf('Open word2vec file %s with %d columns...',filename,columns));
str = extractFileText(filename,'Encoding', 'UTF-8');
lines = split(str,newline);
lines(1:2)=[];

disp(sprintf('Extracting word-embeddings...'));

num_words=size(lines,1);
wordlist=cell(num_words,1);
vectors_matrix=nan(num_words,columns);

for i=1:num_words
    current_line=lines(i);
    if strlength(current_line)>(columns+1)*2
        elements = split(current_line," ");
        wordlist{i}=elements{1};
        elements([1,end])=[];
        numbers = cellfun(@str2num,elements);
        vectors_matrix(i,:)=numbers;
    end
end

clear numbers elements current_line lines str


if stemming==1
    disp(sprintf('Stemming the vocabulary in %s...',lang));
    wordlist_stem=cell(size(wordlist));
    for i=1:num_words
        
        if ITA==1
            wordlist_stem{i}=SNLP_stemming_ita(wordlist{i});
        end
        if ENG==1
            wordlist_stem{i}=SNLP_stemming_eng(wordlist{i});
        end
        if FRA==1
            wordlist_stem{i}=SNLP_stemming_fra(wordlist{i});
        end
        
    end
end


filename_root=strsplit(filename,'.');
filename_mat=[filename_root{1},'.mat'];

disp(sprintf('Saving word-embeddings in %s...',filename_mat));

if stemming==1
    save(filename_mat,'vectors_matrix','wordlist_stem','wordlist','num_words','filename','-v7.3');
else
    save(filename_mat,'vectors_matrix','wordlist','num_words','filename','-v7.3');
end

end
